name: booking
description: A new Flutter application.



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  nb_utils: 3.2.11+4
  cached_network_image: ^2.3.1
  flutter_svg: 0.18.1
  html: 0.14.0+3
  google_fonts: 1.1.0
  google_maps_flutter: 0.5.21+3
  flutter_statusbarcolor: 0.2.3
#  admob_flutter: 1.0.0
  clustering_google_maps: 0.1.2
  flutter_staggered_grid_view: 0.3.2
  flutter_staggered_animations: 0.1.2
  dots_indicator: ^0.0.4
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  provider: ^4.3.2+3
  google_maps_webservice: ^0.0.19
  shared_preferences: ^0.5.12+4
  geolocator: ^6.1.13
  geocoder: ^0.2.1



  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner: ^1.9.0



flutter:


  uses-material-design: true
